type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "The First-Class Scholarship for Academic Excellence"
subtitle = "Central University of Finance and Economics"
date = "2025.9"
content = ""

[[items]]
title = "National Scholarship"
subtitle = "Ministry of Education, China"
date = "2024.11"
content = "Top 1%"

[[items]]
title = "The First-Class Scholarship for Doctoral Entrance"
subtitle = "Central University of Finance and Economics"
date = "2024.9"
content = ""

[[items]]
title = "The First-Class Scholarship for Academic Excellence"
subtitle = "Central University of Finance and Economics"
date = "2023.9"
content = ""

[[items]]
title = "The First-Class Scholarship for Graduate Entrance"
subtitle = "Central University of Finance and Economics"
date = "2022.9"
content = ""
