type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "中央财经大学二年级及以上研究生学业一等奖学金"
subtitle = "中央财经大学"
date = "2025.9"
content = "研究生学业奖学金，面向对象为纳入全国研究生招生计划的全日制研究生，用于激励研究生勤奋学习、潜心科研、勇于创新、积极进取，在全面实行研究生教育收费制度的情况下更好地支持研究生顺利完成学业。 "

[[items]]
title = "博士研究生国家奖学金"
subtitle = "国家教育部、财政部"
date = "2024.11"
content = "研究生国家奖学金是由中华人民共和国教育部、财政部共同设立的奖学金项目，用于奖励表现优异的全日制研究生，旨在发展中国特色研究生教育，促进研究生培养机制改革，提高研究生培养质量，激励研究生求真务实、勤奋笃学、专心科研、积极进取。"

[[items]]
title = "中央财经大学研究生新生一等入学奖学金"
subtitle = "中央财经大学"
date = "2024.9"
content = ""

[[items]]
title = "中央财经大学二年级及以上研究生学业一等奖学金"
subtitle = "中央财经大学"
date = "2023.9"
content = "研究生学业奖学金，面向对象为纳入全国研究生招生计划的全日制研究生，用于激励研究生勤奋学习、潜心科研、勇于创新、积极进取，在全面实行研究生教育收费制度的情况下更好地支持研究生顺利完成学业。 "

[[items]]
title = "中央财经大学研究生新生一等入学奖学金"
subtitle = "中央财经大学"
date = "2022.9"
content = ""
