type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "中央财经大学二年级及以上研究生学业一等奖学金"
subtitle = "中央财经大学"
date = "2025.9"
content = ""

[[items]]
title = "博士研究生国家奖学金"
subtitle = "国家教育部、财政部"
date = "2024.11"
content = ""

[[items]]
title = "中央财经大学研究生新生一等入学奖学金"
subtitle = "中央财经大学"
date = "2024.9"
content = ""

[[items]]
title = "中央财经大学二年级及以上研究生学业一等奖学金"
subtitle = "中央财经大学"
date = "2023.9"
content = ""

[[items]]
title = "中央财经大学研究生新生一等入学奖学金"
subtitle = "中央财经大学"
date = "2022.9"
content = ""
