type = "card"
title = "教学"
description = "我曾参与授课或助教的课程。"

[[items]]
title = "国际贸易"
subtitle = "助教"
date = "Fall 2023 & Fall 2024"
content = "该课程为本科生与研究生选修课程，负责指导约 60 名本科生与 30 名研究生。每学期主持 1–2 次习题课，课余时间为学生提供答疑辅导，并协助任课教师批阅作业及期末考试试卷。"
tags = ["本科生", "研究生", "国际贸易"]

[[items]]
title = "货币经济学"
subtitle = "助教"
date = "Spring 2024"
content = "该课程为本科生选修课程，负责指导约 60 名本科生。每学期主持 1–2 次习题课，课余时间为学生提供答疑辅导，并协助任课教师批阅作业及期末考试试卷。"
tags = ["本科生", "货币经济学"]

[[items]]
title = "高级金融理论"
subtitle = "助教"
date = "Fall 2024 & Spring 2025"
content = "该课程为研究生必修课程，负责指导约 30 名研究生。每学期主持 2–3 次习题课，课余时间为学生提供答疑辅导。同时与任课教师共同设计课程考核内容与评估方案，协助批阅作业及期末考试试卷。"
tags = ["研究生", "金融学"]